apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-mr-raczylo-combinding
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-mr-raczylo-com'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-cm-raczylo-com'
  namespace: '{{ .Release.Namespace }}'