apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-raczylo.com-clusterimageexport-editor-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - raczylo.com
  resources:
  - clusterimageexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - raczylo.com
  resources:
  - clusterimageexports/status
  verbs:
  - get
  - patch
  - update
  - watch