apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-cm-raczylo-com
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.cmRaczyloCom.serviceAccount.annotations | nindent 4 }}