apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-auth-raczylobinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-auth-raczylo
subjects:
  - kind: ServiceAccount
    name: cm-raczylo-com
    namespace: system
