# permissions for end users to edit clusterimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-images-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: raczylo.com-clusterimage-editor-role
rules:
  - apiGroups:
      - raczylo.com
    resources:
      - clusterimages
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - raczylo.com
    resources:
      - clusterimages/status
    verbs:
      - get
