---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: impex-mgr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - raczylo.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - raczylo.com
  resources:
  - '*/finalizers'
  verbs:
  - update
- apiGroups:
  - raczylo.com
  resources:
  - '*/status'
  verbs:
  - get
  - patch
  - update
