---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mr-raczylo-com
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - raczylo.com
  resources:
  - clusterimageexports
  - clusterimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - raczylo.com
  resources:
  - clusterimageexports/finalizers
  verbs:
  - update
- apiGroups:
  - raczylo.com
  resources:
  - clusterimageexports/status
  verbs:
  - get
  - patch
  - update
