apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-images-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: cm-raczylo-com
  namespace: system
